name: Docker Image CI
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "feature/initial" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tag_name
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/itau-gt8-challenge:latest
